/**
 * Meta Ads Manager 캠페인 빌더 — 필드 스키마
 * - FULL_COLUMNS: export 파일에 그대로 들어가는 전체 422개 컬럼 순서 (Meta 템플릿 그대로)
 * - FIELD_GROUPS: UI에 표시할 필드들을 레벨(campaign/adset/ad)과 카테고리(핵심/접힘)로 분류
 * - STATIC_DEFAULTS: 거의 항상 동일한 값 (브랜드 무관)
 */

const FULL_COLUMNS = [
  "Campaign ID",
  "Creation Package Config ID",
  "Campaign Name",
  "Special Ad Categories",
  "Special Ad Category Country",
  "Campaign Status",
  "Campaign Objective",
  "Buying Type",
  "Campaign Spend Limit",
  "Campaign Daily Budget",
  "Campaign Lifetime Budget",
  "Campaign Bid Strategy",
  "Tags",
  "Campaign Is Using L3 Schedule",
  "Campaign Start Time",
  "Campaign Stop Time",
  "Product Catalog ID",
  "Campaign Page ID",
  "New Objective",
  "Buy With Prime Type",
  "Is Budget Scheduling Enabled For Campaign",
  "Campaign High Demand Periods",
  "Buy With Integration Partner",
  "Ad Set ID",
  "Ad Set Run Status",
  "Ad Set Lifetime Impressions",
  "Ad Set Name",
  "Ad Set Time Start",
  "Ad Set Time Stop",
  "Ad Set Daily Budget",
  "Destination Type",
  "Ad Set Lifetime Budget",
  "Rate Card",
  "Ad Set Schedule",
  "Use Accelerated Delivery",
  "Frequency Control",
  "Ad Set Minimum Spend Limit",
  "Ad Set Maximum Spend Limit",
  "Is Budget Scheduling Enabled For Ad Set",
  "Ad Set High Demand Periods",
  "Link Object ID",
  "Optimized Conversion Tracking Pixels",
  "Optimized Custom Conversion ID",
  "Optimized Pixel Rule",
  "Optimized Event",
  "Custom Event Name",
  "Link",
  "Application ID",
  "Product Set ID",
  "Place Page Set ID",
  "Object Store URL",
  "Offer ID",
  "Offline Event Data Set ID",
  "Countries",
  "Cities",
  "Regions",
  "Electoral Districts",
  "Zip",
  "Addresses",
  "Geo Markets (DMA)",
  "Global Regions",
  "Large Geo Areas",
  "Medium Geo Areas",
  "Small Geo Areas",
  "Metro Areas",
  "Neighborhoods",
  "Subneighborhoods",
  "Subcities",
  "Location Types",
  "Location Cluster IDs",
  "Location Set IDs",
  "Excluded Countries",
  "Excluded Cities",
  "Excluded Large Geo Areas",
  "Excluded Medium Geo Areas",
  "Excluded Metro Areas",
  "Excluded Small Geo Areas",
  "Excluded Subcities",
  "Excluded Neighborhoods",
  "Excluded Subneighborhoods",
  "Excluded Regions",
  "Excluded Electoral Districts",
  "Excluded Zip",
  "Excluded Addresses",
  "Excluded Geo Markets (DMA)",
  "Excluded Global Regions",
  "Excluded Location Cluster IDs",
  "Gender",
  "Age Min",
  "Age Max",
  "Education Status",
  "Fields of Study",
  "Education Schools",
  "Work Job Titles",
  "Work Employers",
  "College Start Year",
  "College End Year",
  "Interested In",
  "Relationship",
  "Family Statuses",
  "Industries",
  "Life Events",
  "Income",
  "Multicultural Affinity",
  "Household Composition",
  "Behaviors",
  "Connections",
  "Excluded Connections",
  "Friends of Connections",
  "Locales",
  "Site Category",
  "Unified Interests",
  "Excluded User AdClusters",
  "Broad Category Clusters",
  "Targeting Categories - ALL OF",
  "Custom Audiences",
  "Excluded Custom Audiences",
  "Flexible Inclusions",
  "Flexible Exclusions",
  "Advantage Audience",
  "Individual Setting",
  "Age Range",
  "Targeting Optimization",
  "Targeting Relaxation",
  "Product Audience Specs",
  "Excluded Product Audience Specs",
  "Targeted Business Locations",
  "Dynamic Audiences",
  "Excluded Dynamic Audiences",
  "Beneficiary",
  "Payer",
  "Publisher Platforms",
  "Facebook Positions",
  "Instagram Positions",
  "Audience Network Positions",
  "Messenger Positions",
  "Oculus Positions",
  "Device Platforms",
  "User Device",
  "Excluded User Device",
  "User Operating System",
  "User OS Version",
  "Wireless Carrier",
  "Excluded Publisher Categories",
  "Brand Safety Inventory Filtering Levels",
  "Optimization Goal",
  "Attribution Spec",
  "Billing Event",
  "Bid Amount",
  "Ad Set Bid Strategy",
  "Regional Regulated Categories",
  "Advertiser (financial ads in Australia)",
  "Payer (financial ads in Australia)",
  "Beneficiary (financial ads in Taiwan)",
  "Payer (financial ads in Taiwan)",
  "Advertiser (Taiwan)",
  "Payer (Taiwan)",
  "Advertiser (Singapore)",
  "Payer (Singapore)",
  "Advertiser (securities ads in India)",
  "Payer (securities ads in India)",
  "Beneficiary (selected locations)",
  "Payer (selected locations)",
  "Story ID",
  "Ad ID",
  "Ad Status",
  "Preview Link",
  "Instagram Preview Link",
  "Ad Name",
  "Title",
  "Body",
  "Display Link",
  "Link Description",
  "Optimize text per person",
  "Retailer IDs",
  "Post Click Item Headline",
  "Post Click Item Description",
  "Conversion Tracking Pixels",
  "Optimized Ad Creative",
  "Image Hash",
  "Image File Name",
  "Image Crops",
  "Video Thumbnail URL",
  "Instagram Platform Image Hash",
  "Instagram Platform Image Crops",
  "Instagram Platform Image URL",
  "Carousel Delivery Mode",
  "Creative Type",
  "URL Tags",
  "View Tags",
  "Event ID",
  "Video ID",
  "Video File Name",
  "Instagram Account ID",
  "Instagram Account ID (New)",
  "Mobile App Deep Link",
  "Product Link",
  "App Link Destination",
  "Call Extension Phone Data ID",
  "Call to Action",
  "Additional Call To Action 5",
  "Additional Call To Action 6",
  "Additional Call To Action 7",
  "Additional Call To Action 8",
  "Additional Call To Action 9",
  "Call to Action Link",
  "Call to Action WhatsApp Number",
  "Additional Custom Tracking Specs",
  "Video Retargeting",
  "Lead Form ID",
  "Permalink",
  "Force Single Link",
  "Format Option",
  "Dynamic Ad Voice",
  "Creative Optimization",
  "Template URL",
  "Android App Name",
  "Android Package Name",
  "Deep Link For Android",
  "Facebook App ID",
  "iOS App Name",
  "iOS App Store ID",
  "Deep Link For iOS",
  "iPad App Name",
  "iPad App Store ID",
  "Deep Link For iPad",
  "iPhone App Name",
  "iPhone App Store ID",
  "Deep Link For iPhone",
  "Deep link to website",
  "Windows Store ID",
  "Windows App Name",
  "Deep Link For Windows Phone",
  "Add End Card",
  "Dynamic Ads Ad Context",
  "Page Welcome Message",
  "App Destination",
  "App Destination Page ID",
  "Use Page as Actor",
  "Image Overlay Template",
  "Image Overlay Text Type",
  "Image Overlay Text Font",
  "Image Overlay Position",
  "Image Overlay Theme Color",
  "Image Overlay Float With Margin",
  "Image Layer 1 - layer_type",
  "Image Layer 1 - image_source",
  "Image Layer 1 - overlay_shape",
  "Image Layer 1 - text_font",
  "Image Layer 1 - shape_color",
  "Image Layer 1 - text_color",
  "Image Layer 1 - content_type",
  "Image Layer 1 - price",
  "Image Layer 1 - low_price",
  "Image Layer 1 - high_price",
  "Image Layer 1 - frame_source",
  "Image Layer 1 - frame_image_hash",
  "Image Layer 1 - scale",
  "Image Layer 1 - blending_mode",
  "Image Layer 1 - opacity",
  "Image Layer 1 - overlay_position",
  "Image Layer 1 - pad_image",
  "Image Layer 1 - crop_image",
  "Image Layer 2 - layer_type",
  "Image Layer 2 - image_source",
  "Image Layer 2 - overlay_shape",
  "Image Layer 2 - text_font",
  "Image Layer 2 - shape_color",
  "Image Layer 2 - text_color",
  "Image Layer 2 - content_type",
  "Image Layer 2 - price",
  "Image Layer 2 - low_price",
  "Image Layer 2 - high_price",
  "Image Layer 2 - frame_source",
  "Image Layer 2 - frame_image_hash",
  "Image Layer 2 - scale",
  "Image Layer 2 - blending_mode",
  "Image Layer 2 - opacity",
  "Image Layer 2 - overlay_position",
  "Image Layer 2 - pad_image",
  "Image Layer 2 - crop_image",
  "Image Layer 3 - layer_type",
  "Image Layer 3 - image_source",
  "Image Layer 3 - overlay_shape",
  "Image Layer 3 - text_font",
  "Image Layer 3 - shape_color",
  "Image Layer 3 - text_color",
  "Image Layer 3 - content_type",
  "Image Layer 3 - price",
  "Image Layer 3 - low_price",
  "Image Layer 3 - high_price",
  "Image Layer 3 - frame_source",
  "Image Layer 3 - frame_image_hash",
  "Image Layer 3 - scale",
  "Image Layer 3 - blending_mode",
  "Image Layer 3 - opacity",
  "Image Layer 3 - overlay_position",
  "Image Layer 3 - pad_image",
  "Image Layer 3 - crop_image",
  "Product 1 - Link",
  "Product 1 - Name",
  "Product 1 - Description",
  "Product 1 - Image Hash",
  "Product 1 - Image Crops",
  "Product 1 - Video ID",
  "Product 1 - Call To Action Link",
  "Product 1 - Mobile App Deep Link",
  "Product 1 - Display Link",
  "Product 1 - Place Data",
  "Product 1 - Is Static Card",
  "Product 2 - Link",
  "Product 2 - Name",
  "Product 2 - Description",
  "Product 2 - Image Hash",
  "Product 2 - Image Crops",
  "Product 2 - Video ID",
  "Product 2 - Call To Action Link",
  "Product 2 - Mobile App Deep Link",
  "Product 2 - Display Link",
  "Product 2 - Place Data",
  "Product 2 - Is Static Card",
  "Product 3 - Link",
  "Product 3 - Name",
  "Product 3 - Description",
  "Product 3 - Image Hash",
  "Product 3 - Image Crops",
  "Product 3 - Video ID",
  "Product 3 - Call To Action Link",
  "Product 3 - Mobile App Deep Link",
  "Product 3 - Display Link",
  "Product 3 - Place Data",
  "Product 3 - Is Static Card",
  "Product 4 - Link",
  "Product 4 - Name",
  "Product 4 - Description",
  "Product 4 - Image Hash",
  "Product 4 - Image Crops",
  "Product 4 - Video ID",
  "Product 4 - Call To Action Link",
  "Product 4 - Mobile App Deep Link",
  "Product 4 - Display Link",
  "Product 4 - Place Data",
  "Product 4 - Is Static Card",
  "Product 5 - Link",
  "Product 5 - Name",
  "Product 5 - Description",
  "Product 5 - Image Hash",
  "Product 5 - Image Crops",
  "Product 5 - Video ID",
  "Product 5 - Call To Action Link",
  "Product 5 - Mobile App Deep Link",
  "Product 5 - Display Link",
  "Product 5 - Place Data",
  "Product 5 - Is Static Card",
  "Product 6 - Link",
  "Product 6 - Name",
  "Product 6 - Description",
  "Product 6 - Image Hash",
  "Product 6 - Image Crops",
  "Product 6 - Video ID",
  "Product 6 - Call To Action Link",
  "Product 6 - Mobile App Deep Link",
  "Product 6 - Display Link",
  "Product 6 - Place Data",
  "Product 6 - Is Static Card",
  "Product 7 - Link",
  "Product 7 - Name",
  "Product 7 - Description",
  "Product 7 - Image Hash",
  "Product 7 - Image Crops",
  "Product 7 - Video ID",
  "Product 7 - Call To Action Link",
  "Product 7 - Mobile App Deep Link",
  "Product 7 - Display Link",
  "Product 7 - Place Data",
  "Product 7 - Is Static Card",
  "Product 8 - Link",
  "Product 8 - Name",
  "Product 8 - Description",
  "Product 8 - Image Hash",
  "Product 8 - Image Crops",
  "Product 8 - Video ID",
  "Product 8 - Call To Action Link",
  "Product 8 - Mobile App Deep Link",
  "Product 8 - Display Link",
  "Product 8 - Place Data",
  "Product 8 - Is Static Card",
  "Product 9 - Link",
  "Product 9 - Name",
  "Product 9 - Description",
  "Product 9 - Image Hash",
  "Product 9 - Image Crops",
  "Product 9 - Video ID",
  "Product 9 - Call To Action Link",
  "Product 9 - Mobile App Deep Link",
  "Product 9 - Display Link",
  "Product 9 - Place Data",
  "Product 9 - Is Static Card",
  "Product 10 - Link",
  "Product 10 - Name",
  "Product 10 - Description",
  "Product 10 - Image Hash",
  "Product 10 - Image Crops",
  "Product 10 - Video ID",
  "Product 10 - Call To Action Link",
  "Product 10 - Mobile App Deep Link",
  "Product 10 - Display Link",
  "Product 10 - Place Data",
  "Product 10 - Is Static Card",
  "Product Sales Channel",
  "Additional Dynamic Creative Call To Action Type 5",
  "Additional Dynamic Creative Call To Action Type 6",
  "Additional Dynamic Creative Call To Action Type 7",
  "Additional Dynamic Creative Call To Action Type 8",
  "Additional Dynamic Creative Call To Action Type 9",
  "Degrees of Freedom Type",
  "Creative Destination Type",
  "Creative Onsite Destinations",
  "Mockup ID",
  "Text Transformations",
  "Ad Stop Time",
  "Ad Start Time"
];

// 레벨별, 카테고리별 필드 그룹 정의
// core: 항상 펼쳐진 상태로 노출 (광고주가 매번 주는 정보)
// collapsed: 카테고리로 묶어서 기본 접힘, 필요시 펼쳐서 수정
const FIELD_GROUPS = {
  campaign: {
    core: [
      { key: 'Campaign Name', label: '캠페인 이름', type: 'text', required: true, maxLength: 35 },
      { key: 'Campaign Status', label: '캠페인 상태', type: 'select', options: ['ACTIVE', 'PAUSED'], required: true },
      { key: 'Campaign Daily Budget', label: '일일 예산 (원)', type: 'number' },
      { key: 'Campaign Lifetime Budget', label: '총 예산 (원)', type: 'number' },
      { key: 'Campaign Start Time', label: '캠페인 시작', type: 'datetime' },
      { key: 'Campaign Stop Time', label: '캠페인 종료', type: 'datetime' },
    ],
    collapsedGroups: [
      {
        title: '목표 및 입찰',
        fields: [
          { key: 'Campaign Objective', label: '캠페인 목표', type: 'select', options: ['Traffic', 'Outcome Awareness', 'Outcome Sales', 'Outcome Engagement', 'Outcome Leads', 'Outcome App Promotion'] },
          { key: 'Buying Type', label: '구매 유형', type: 'select', options: ['AUCTION', 'RESERVED'] },
          { key: 'Campaign Bid Strategy', label: '캠페인 입찰 전략', type: 'select', options: ['Highest volume or value', 'Cost per result goal', 'Bid cap', 'ROAS goal'] },
        ]
      },
      {
        title: '고급 설정',
        fields: [
          { key: 'New Objective', label: 'New Objective', type: 'select', options: ['Yes', 'No'] },
          { key: 'Buy With Prime Type', label: 'Buy With Prime', type: 'select', options: ['NONE'] },
          { key: 'Is Budget Scheduling Enabled For Campaign', label: '예산 스케줄링 사용', type: 'select', options: ['No', 'Yes'] },
          { key: 'Campaign High Demand Periods', label: 'High Demand Periods', type: 'text' },
          { key: 'Buy With Integration Partner', label: 'Integration Partner', type: 'text' },
        ]
      }
    ]
  },

  adset: {
    core: [
      { key: 'Ad Set Name', label: '광고 세트 이름', type: 'text', required: true, maxLength: 35 },
      { key: 'Ad Set Run Status', label: '광고 세트 상태', type: 'select', options: ['ACTIVE', 'PAUSED'], required: true },
      { key: 'Ad Set Daily Budget', label: '광고 세트 일일 예산 (원)', type: 'number' },
      { key: 'Ad Set Lifetime Budget', label: '광고 세트 총 예산 (원)', type: 'number' },
      { key: 'Ad Set Time Start', label: '광고 세트 시작', type: 'datetime' },
      { key: 'Ad Set Time Stop', label: '광고 세트 종료', type: 'datetime' },
      { key: 'Link', label: '랜딩 URL', type: 'url', required: true },
    ],
    collapsedGroups: [
      {
        title: '타겟팅 — 위치/인구통계',
        fields: [
          { key: 'Countries', label: '타겟 국가 (콤마 구분, ISO 2자리)', type: 'text' },
          { key: 'Gender', label: '성별', type: 'select', options: ['', 'Women', 'Men'] },
          { key: 'Age Min', label: '최소 연령', type: 'number' },
          { key: 'Age Max', label: '최대 연령', type: 'number' },
          { key: 'Location Types', label: 'Location Types', type: 'text' },
        ]
      },
      {
        title: '타겟팅 — 오디언스',
        fields: [
          { key: 'Custom Audiences', label: '맞춤 타겟', type: 'text' },
          { key: 'Excluded Custom Audiences', label: '제외 맞춤 타겟', type: 'text' },
          { key: 'Flexible Inclusions', label: 'Flexible Inclusions', type: 'text' },
          { key: 'Advantage Audience', label: 'Advantage Audience', type: 'select', options: ['0', '1'] },
          { key: 'Targeting Optimization', label: 'Targeting Optimization', type: 'text' },
          { key: 'Targeting Relaxation', label: 'Targeting Relaxation', type: 'text' },
        ]
      },
      {
        title: '게재 위치',
        fields: [
          { key: 'Publisher Platforms', label: 'Publisher Platforms', type: 'text' },
          { key: 'Facebook Positions', label: 'Facebook Positions', type: 'text' },
          { key: 'Instagram Positions', label: 'Instagram Positions', type: 'text' },
          { key: 'Messenger Positions', label: 'Messenger Positions', type: 'text' },
          { key: 'Device Platforms', label: 'Device Platforms', type: 'text' },
        ]
      },
      {
        title: '최적화 및 입찰',
        fields: [
          { key: 'Optimization Goal', label: '최적화 목표', type: 'select', options: ['LINK_CLICKS', 'REACH', 'IMPRESSIONS', 'CONVERSIONS', 'LANDING_PAGE_VIEWS'] },
          { key: 'Billing Event', label: '청구 이벤트', type: 'select', options: ['IMPRESSIONS', 'LINK_CLICKS'] },
          { key: 'Ad Set Bid Strategy', label: '광고 세트 입찰 전략', type: 'select', options: ['Highest volume or value', 'Cost per result goal', 'Bid cap', 'ROAS goal'] },
          { key: 'Attribution Spec', label: 'Attribution Spec', type: 'text' },
          { key: 'Frequency Control', label: 'Frequency Control', type: 'text' },
        ]
      },
      {
        title: '기타 설정',
        fields: [
          { key: 'Link Object ID', label: 'Link Object ID (페이지 ID)', type: 'text' },
          { key: 'Destination Type', label: 'Destination Type', type: 'text' },
          { key: 'Use Accelerated Delivery', label: 'Accelerated Delivery', type: 'select', options: ['No', 'Yes'] },
          { key: 'Is Budget Scheduling Enabled For Ad Set', label: '예산 스케줄링 사용', type: 'select', options: ['No', 'Yes'] },
          { key: 'Ad Set High Demand Periods', label: 'High Demand Periods', type: 'text' },
          { key: 'Brand Safety Inventory Filtering Levels', label: 'Brand Safety Filtering', type: 'text' },
          { key: 'Regional Regulated Categories', label: 'Regional Regulated Categories', type: 'text' },
          { key: 'Beneficiary', label: 'Beneficiary', type: 'text' },
          { key: 'Payer', label: 'Payer', type: 'text' },
        ]
      }
    ]
  },

  ad: {
    core: [
      { key: 'Ad Name', label: '광고 이름', type: 'text', required: true, maxLength: 35 },
      { key: 'Ad Status', label: '광고 상태', type: 'select', options: ['ACTIVE', 'PAUSED'], required: true },
      { key: '__creative__', label: '소재 (드라이브 파일)', type: 'creative_picker', required: true },
      { key: 'Title', label: '제목', type: 'text', maxLength: 25, required: true },
      { key: 'Body', label: '본문', type: 'textarea', maxLength: 500, required: true },
      { key: 'Call to Action', label: '행동 유도 버튼', type: 'select', options: ['SHOP_NOW', 'LEARN_MORE', 'SEE_DETAILS', 'SIGN_UP', 'DOWNLOAD', 'GET_OFFER', 'SUBSCRIBE', 'WATCH_MORE'] },
    ],
    collapsedGroups: [
      {
        title: '소재 상세',
        fields: [
          { key: 'Creative Type', label: 'Creative Type', type: 'select', options: ['Video Page Post Ad', 'Link Page Post Ad'] },
          { key: 'Instagram Account ID', label: 'Instagram Account ID', type: 'text' },
          { key: 'Optimize text per person', label: '텍스트 개인화 최적화', type: 'select', options: ['No', 'Yes'] },
          { key: 'Optimized Ad Creative', label: 'Optimized Ad Creative', type: 'text' },
          { key: 'Use Page as Actor', label: 'Use Page as Actor', type: 'select', options: ['No', 'Yes'] },
          { key: 'Video Retargeting', label: 'Video Retargeting', type: 'select', options: ['No', 'Yes'] },
          { key: 'Add End Card', label: 'Add End Card', type: 'text' },
        ]
      },
      {
        title: '캐러셀 / 다중 이미지 (필요시)',
        fields: [
          { key: 'Creative Optimization', label: 'Creative Optimization (다중 이미지/링크)', type: 'select', options: ['', '예', '아니요'] },
          { key: 'Carousel Delivery Mode', label: 'Carousel Delivery Mode', type: 'text' },
          { key: 'Product 1 - Link', label: '카드1 - 링크', type: 'url' },
          { key: 'Product 1 - Name', label: '카드1 - 제목', type: 'text' },
          { key: 'Product 2 - Link', label: '카드2 - 링크', type: 'url' },
          { key: 'Product 2 - Name', label: '카드2 - 제목', type: 'text' },
          { key: 'Product 3 - Link', label: '카드3 - 링크', type: 'url' },
          { key: 'Product 3 - Name', label: '카드3 - 제목', type: 'text' },
        ]
      },
      {
        title: '고급 추적',
        fields: [
          { key: 'Additional Custom Tracking Specs', label: 'Additional Custom Tracking Specs', type: 'text' },
          { key: 'Degrees of Freedom Type', label: 'Degrees of Freedom Type', type: 'text' },
          { key: 'Story ID', label: 'Story ID', type: 'text' },
        ]
      }
    ]
  }
};

// 모든 레벨에 공통으로 존재하지만 사용자가 직접 건드릴 일이 거의 없는 ID/메타 필드
const ID_FIELDS = {
  campaign: 'Campaign ID',
  adset: 'Ad Set ID',
  ad: 'Ad ID',
};

// 거의 항상 고정인 값 (브랜드 디폴트에 없으면 이걸로 채움)
const STATIC_DEFAULTS = {
  'Buying Type': 'AUCTION',
  'Billing Event': 'IMPRESSIONS',
  'Attribution Spec': '[{"event_type":"CLICK_THROUGH","window_days":1}]',
  'Destination Type': 'UNDEFINED',
  'New Objective': 'Yes',
  'Buy With Prime Type': 'NONE',
  'Optimize text per person': 'No',
  'Use Accelerated Delivery': 'No',
  'Video Retargeting': 'No',
  'Use Page as Actor': 'No',
  'Location Types': 'home, recent',
  'Campaign Objective': 'Traffic',
  'Optimization Goal': 'LINK_CLICKS',
  'Creative Type': 'Video Page Post Ad',
  'Ad Set Bid Strategy': 'Highest volume or value',
  'Is Budget Scheduling Enabled For Campaign': 'No',
  'Is Budget Scheduling Enabled For Ad Set': 'No',
  'Campaign Status': 'ACTIVE',
  'Ad Set Run Status': 'ACTIVE',
  'Ad Status': 'ACTIVE',
};

window.FULL_COLUMNS = FULL_COLUMNS;
window.FIELD_GROUPS = FIELD_GROUPS;
window.ID_FIELDS = ID_FIELDS;
window.STATIC_DEFAULTS = STATIC_DEFAULTS;
